@TicketSystem_HostAddress = http://localhost:5297

GET {{TicketSystem_HostAddress}}/weatherforecast/
Accept: application/json

###
POST  http://localhost:5297/api/Employee-Register
content-type: application/json; charset=utf-8 
Authorization: Bearer ""
